name: Github Release

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.3.2"

jobs:
  create-build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [windows]
        include:
          # - os: macos-10.15 # Catalina
          #   target: macOS
          #   build_target: macos
          #   build_path: build/macos/Build/Products/Release
          #   asset_extension: .zip
          #   asset_content_type: application/zip
          #   build_options: 
          - os: windows-latest
            target: windows
            build_target: windows
            build_path: build\windows\runner\Release
            asset_extension: .zip
            asset_content_type: application/zip
            build_options: 
          # - os: ubuntu-latest
          #   target: linux
          #   build_target: linux
          #   build_path: build/linux/x64/release/bundle
          #   asset_extension: .tar.gz
          #   asset_content_type: application/gzip
          #   build_options: 
          # - os: ubuntu-latest
          #   target: android
          #   build_target: apk
          #   build_path: build/app/outputs/flutter-apk
          #   asset_extension: .apk
          #   asset_content_type: application/vnd.android.package-archive
          #   build_options: --flavor=play
      fail-fast: false
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: flutter-stable-${{ matrix.os }}-${{ env.FLUTTER_VERSION }}
      - name: Get Version
        shell: bash
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/v') }}" = "true" ]; then
              echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          else
              echo "VERSION=preview" >> $GITHUB_ENV
          fi
      - run: echo "VERSION = $VERSION"
        shell: bash
      - name: Install Linux dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev

      - name: Install Android dependencies
        if: matrix.target == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Enable desktop support
        if: matrix.target != 'android'
        run: |
          flutter config --enable-linux-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Keystore for Android
        if: matrix.target == 'android'
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: Generate git info
        run:  dart ./scripts/gen_git_info.dart

      - run: flutter pub get
      - run: dart ./scripts/patch_before_build.dart ${{ matrix.target }} ${{ github.ref }}
      - run: flutter pub get
      - run: flutter build ${{ matrix.build_target }} -v --release ${{ matrix.build_options }}

      # Package the build.
      - name: Copy VC redistributables to release directory for Windows
        if: matrix.target == 'windows'
        run: |
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .
        working-directory: ${{ matrix.build_path }}
      - name: Rename build for Android
        if: matrix.target == 'android'
        run: mv app-play-release.apk $GITHUB_WORKSPACE/painter-$VERSION-${{ matrix.target }}.apk
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for Linux
        if: matrix.target == 'linux'
        run: tar czf $GITHUB_WORKSPACE/painter-$VERSION-${{ matrix.target }}.tar.gz *
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for macOS
        if: matrix.target == 'macOS'
        run: ditto -c -k --sequesterRsrc --keepParent Painter.app $GITHUB_WORKSPACE/painter-$VERSION-${{ matrix.target }}.zip
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for Windows
        if: matrix.target == 'windows'
        run: compress-archive -Path * -DestinationPath ${env:GITHUB_WORKSPACE}\painter-${env:VERSION}-${{ matrix.target }}.zip
        working-directory: ${{ matrix.build_path }}

      - name: Generate SHA1
        run: dart ./scripts/gen_sha1.dart ./painter-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.asset_extension }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: painter-${{ env.VERSION }}-${{ matrix.target }}
          if-no-files-found: error
          path: ./painter-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.asset_extension }}*

  publish-release:
    name: Publish Release
    needs: create-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u +"%Y/%m/%d %H:%M:%S %Z")"
      - uses: actions/download-artifact@v3
      - run: ls -l -R

      - name: Delete previous canary build
        if: github.ref == 'refs/heads/main'
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: canary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Publish Canary
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: canary
          name: Painter Preview
          body: Built at ${{ steps.get-date.outputs.date }}
          draft: false
          prerelease: true
          artifacts: "painter-*/*"

      - name: Publish ${GITHUB_REF/refs\/tags\/v/}
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          body: Built at ${{ steps.get-date.outputs.date }}
          artifacts: "painter-*/*"
